name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to release'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: "${{ github.events.inputs.tag }}"
      - name: set up yq - portable yaml processor
        uses: mikefarah/yq@3.4.1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests